app/extras/forms.py
# app/extras/forms.py
# coding: utf-8

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class EstadoCivilForm(FlaskForm):
    """
    Form para agregar o modificar EstadoCivil
    """
    nombre_ec = StringField(u'Nombre', validators=[DataRequired()])
    descripcion_ec = StringField(u'Descripción')
    submit = SubmitField(u'Aceptar')


class TipoMiembroForm(FlaskForm):
    """
    Form para agregar o modificar Tipo de Miembro
    """
    nombre_tm = StringField(u'Nombre', validators=[DataRequired()])
    descripcion_tm = StringField(u'Descripción')
    submit = SubmitField(u'Aceptar')


class RolFamiliarForm(FlaskForm):
    """
    Form para agregar o modificar Rol Familiar
    """
    nombre_rf = StringField(u'Nombre', validators=[DataRequired()])
    descripcion_rf = StringField(u'Descripción')
    submit = SubmitField(u'Aceptar')


class TipoFamiliaForm(FlaskForm):
    """
    Form para agregar o modificar Tipo de Familia
    """
    nombre_tf = StringField(u'Nombre', validators=[DataRequired()])
    descripcion_tf = StringField(u'Descripción')
    submit = SubmitField(u'Aceptar')

app/extras/__init__.py
# app/extras/__init__.py

from flask import Blueprint

extras = Blueprint('extras', __name__)

from . import views

app/extras/views.py
# app/extras/views.py
# coding: utf-8

from flask import flash
from flask import redirect, render_template, url_for
from flask_login import current_user, login_required

from app.extras import extras
from app.extras.forms import EstadoCivilForm, TipoMiembroForm, RolFamiliarForm
from app.extras.forms import TipoFamiliaForm
from app import db
from app.models import EstadoCivil, TipoMiembro, RolFamiliar, TipoFamilia


def check_edit_or_admin():
    """
    Si no es admin o editor lo manda al inicio
    """
    if not current_user.get_urole() >= 1:
        return redirect(url_for("home.hub"))


# SECCION: *****ESTADOS CIVILES*****

@extras.route('/extras/estadosciviles', methods=['GET'])
@login_required
def ver_estadosciviles():
    """
    Ver una lista de todos los estados civiles
    con la opción de modificar, borrar o agregar uno nuevo
    """
    check_edit_or_admin()

    # de arranque carga el listado
    flag_listar = True

    query_ecivil = EstadoCivil.query.all()

    return render_template('extras/estadosciviles/base_estadosciviles.html',
                           estadosciviles=query_ecivil,
                           flag_listar=flag_listar)


@extras.route('/extras/estadosciviles/crear', methods=['GET', 'POST'])
@login_required
def crear_estadocivil():
    """
    Agregar un Estado Civil a la Base de Datos
    """
    check_edit_or_admin()

    # Variable para el template. Para decirle si es Alta o Modif
    flag_crear = True
    flag_listar = False

    form = EstadoCivilForm()
    if form.validate_on_submit():
        obj_ecivil = EstadoCivil(nombre_estado=form.nombre_ec.data,
                                 descripcion_estado=form.descripcion_ec.data)
        try:
            db.session.add(obj_ecivil)
            db.session.commit()
            flash('Has guardado los datos correctamente', 'success')
        except Exception as e:
            flash('Error:', e, 'danger')

        return redirect(url_for('extras.ver_estadosciviles'))

    return render_template(
                'extras/estadosciviles/base_estadosciviles.html',
                add_estadocivil=flag_crear, flag_listar=flag_listar, form=form)


@extras.route('/extras/estadosciviles/modif/<int:id>', methods=['GET', 'POST'])
@login_required
def modif_estadocivil(id):
    """
    Modificar un estado civil
    """
    check_edit_or_admin()

    flag_crear = False
    flag_listar = False

    obj_ecivil = EstadoCivil.query.get_or_404(id)
    form = EstadoCivilForm(obj=obj_ecivil)
    if form.validate_on_submit():
        obj_ecivil.nombre_estado = form.nombre_ec.data
        obj_ecivil.descripcion_estado = form.descripcion_ec.data
        try:
            db.session.commit()
            flash('Has modificado los datos correctamente', 'success')
        except Exception as e:
            flash('Error: ' + str(e), 'danger')

        return redirect(url_for('extras.ver_estadosciviles'))

    form.nombre_ec.data = obj_ecivil.nombre_estado
    form.descripcion_ec.data = obj_ecivil.descripcion_estado
    return render_template(
                'extras/estadosciviles/base_estadosciviles.html',
                add_estadocivil=flag_crear, flag_listar=flag_listar,
                form=form, estadocivil=obj_ecivil)


@extras.route('/extras/estadosciviles/borrar/<int:id>',
              methods=['GET'])
@login_required
def borrar_estadocivil(id):
    """
    Borrar un estado civil
    """
    check_edit_or_admin()

    obj_ecivil = EstadoCivil.query.get_or_404(id)
    try:
        db.session.delete(obj_ecivil)
        db.session.commit()
        flash('Has borrado los datos correctamente', 'success')
    except Exception as e:
        flash('Error: ' + str(e), 'danger')

    return redirect(url_for('extras.ver_estadosciviles'))


# SECCION: *****TIPOS DE MIEMBROS*****
@extras.route('/extras/tiposmiembros', methods=['GET'])
@login_required
def ver_tiposmiembros():
    """
    Ver una lista de todos los tipos de miembros de la iglesia
    con la opción de modificar, borrar o agregar uno nuevo
    """
    check_edit_or_admin()

    # de arranque carga el listado
    flag_listar = True

    query_tmiembro = TipoMiembro.query.all()

    return render_template('extras/tiposmiembros/base_tiposmiembros.html',
                           tiposmiembros=query_tmiembro,
                           flag_listar=flag_listar)


@extras.route('/extras/tiposmiembros/crear', methods=['GET', 'POST'])
@login_required
def crear_tipomiembro():
    """
    Agregar un Tipo de Miembro a la Base de Datos
    """
    check_edit_or_admin()

    # Variable para el template. Para decirle si es Alta o Modif
    flag_crear = True
    flag_listar = False

    form = TipoMiembroForm()
    if form.validate_on_submit():
        obj_tmiembro = TipoMiembro(
                            nombre_tipomiembro=form.nombre_tm.data,
                            descripcion_tipomiembro=form.descripcion_tm.data)
        try:
            db.session.add(obj_tmiembro)
            db.session.commit()
            flash('Has guardado los datos correctamente', 'success')
        except Exception as e:
            flash('Error:', e, 'danger')

        return redirect(url_for('extras.ver_tiposmiembros'))

    return render_template(
                'extras/tiposmiembros/base_tiposmiembros.html',
                add_tipomiembro=flag_crear, flag_listar=flag_listar, form=form)


@extras.route('/extras/tiposmiembros/modif/<int:id>', methods=['GET', 'POST'])
@login_required
def modif_tipomiembro(id):
    """
    Modificar un tipo de miembro
    """
    check_edit_or_admin()

    flag_crear = False
    flag_listar = False

    obj_tmiembro = TipoMiembro.query.get_or_404(id)
    form = TipoMiembroForm(obj=obj_tmiembro)
    if form.validate_on_submit():
        obj_tmiembro.nombre_tipomiembro = form.nombre_tm.data
        obj_tmiembro.descripcion_tipomiembro = form.descripcion_tm.data
        try:
            db.session.commit()
            flash('Has modificado los datos correctamente', 'success')
        except Exception as e:
            flash('Error: ' + str(e), 'danger')

        return redirect(url_for('extras.ver_tiposmiembros'))

    form.nombre_tm.data = obj_tmiembro.nombre_tipomiembro
    form.descripcion_tm.data = obj_tmiembro.descripcion_tipomiembro
    return render_template(
                'extras/tiposmiembros/base_tiposmiembros.html',
                add_tipomiembro=flag_crear, flag_listar=flag_listar,
                form=form, tipomiembro=obj_tmiembro)


@extras.route('/extras/tiposmiembros/borrar/<int:id>', methods=['GET'])
@login_required
def borrar_tipomiembro(id):
    """
    Borrar un tipo de miembros
    """
    check_edit_or_admin()

    obj_tmiembro = TipoMiembro.query.get_or_404(id)
    db.session.delete(obj_tmiembro)

    try:
        db.session.commit()
        flash('Has borrado los datos correctamente', 'success')
    except Exception as e:
        flash('Error: ' + str(e), 'danger')

    return redirect(url_for('extras.ver_tiposmiembros'))


# SECCION: ***** ROLES FAMILIARES *****

@extras.route('/extras/rolesfamiliares', methods=['GET'])
@login_required
def ver_rolesfamiliares():
    """
    Ver una lista de todos los roles familiares de la iglesia
    con la opción de modificar, borrar o agregar uno nuevo
    """
    check_edit_or_admin()

    # de arranque carga el listado
    flag_listar = True

    query_rfamiliar = RolFamiliar.query.all()

    return render_template('extras/rolesfamiliares/base_rolesfamiliares.html',
                           rolesfamiliares=query_rfamiliar,
                           flag_listar=flag_listar)


@extras.route('/extras/rolesfamiliares/crear', methods=['GET', 'POST'])
@login_required
def crear_rolfamiliar():
    """
    Agregar un Rol Familiar a la Base de Datos
    """
    check_edit_or_admin()

    # Variable para el template. Para decirle si es Alta o Modif
    flag_crear = True
    flag_listar = False

    form = RolFamiliarForm()
    if form.validate_on_submit():
        obj_rfamiliar = RolFamiliar(
                            nombre_rolfam=form.nombre_rf.data,
                            descripcion_rolfam=form.descripcion_rf.data)
        try:
            db.session.add(obj_rfamiliar)
            db.session.commit()
            flash('Has guardado los datos correctamente', 'success')
        except Exception as e:
            flash('Error:', e, 'danger')

        return redirect(url_for('extras.ver_rolesfamiliares'))

    return render_template(
                'extras/rolesfamiliares/base_rolesfamiliares.html',
                add_rolfamiliar=flag_crear, flag_listar=flag_listar,
                form=form)


@extras.route('/extras/rolesfamiliares/modif/<int:id>',
              methods=['GET', 'POST'])
@login_required
def modif_rolfamiliar(id):
    """
    Modificar un rol familiar
    """
    check_edit_or_admin()

    flag_crear = False
    flag_listar = False

    obj_rfamiliar = RolFamiliar.query.get_or_404(id)
    form = RolFamiliarForm(obj=obj_rfamiliar)
    if form.validate_on_submit():
        obj_rfamiliar.nombre_rolfam = form.nombre_rf.data
        obj_rfamiliar.descripcion_rolfam = form.descripcion_rf.data
        try:
            db.session.commit()
            flash('Has modificado los datos correctamente', 'success')
        except Exception as e:
            flash('Error: ' + str(e), 'danger')

        return redirect(url_for('extras.ver_rolesfamiliares'))

    form.nombre_rf.data = obj_rfamiliar.nombre_rolfam
    form.descripcion_rf.data = obj_rfamiliar.descripcion_rolfam
    return render_template(
                'extras/rolesfamiliares/base_rolesfamiliares.html',

app/templates/extras/tiposmiembros/agregar_editar_tipomiembro.html
<!-- app/templates/extras/tiposmiembros/agregar_editar_tipomiembro.html -->

{% if current_user.is_authenticated %}
{# En general a todo menos a Seguimiento y Ausencias pueden acceder Editores y Admin #}
{% if current_user.get_urole() >= 1 %}

{% set nombre = "Tipo de Miembro" %}
{% if add_tipomiembro %}
{%    set modo = 'Agregar' %}
{% else %}
{%    set modo = 'Modificar' %}
{% endif %}

<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 my-3 alert alert-primary"> {{modo}} {{nombre}} </h1>
  <div class="col-12">
    <div class="card shadow">
      <div class="card-header py-3">
        <h6 class="font-weight-bold text-primary">
          Datos
        </h6>
      </div>
      <div class="card-body">
        <form class="user" method="POST" role="form" action="">
          {{ form.csrf_token }}
          <div class="form-group">
            {{form.nombre_tm.label}}
            {{ form.nombre_tm(class_="form-control form-control-user") }}
          </div>
          <div class="form-group">
            {{ form.descripcion_tm.label }}
            {{ form.descripcion_tm(class_="form-control form-control-user") }}
          </div>
          <div class="row">
            <div class="col-2"></div>
            <div class="col-4">
              <input type="submit" id="submit" name="submit" class="font-weight-bold btn btn-primary btn-block btn-lg"
                value="Guardar" />
            </div>
            <div class="col-4">
              <a class="font-weight-bold btn btn-danger btn-lg btn-block"
                href="{{ url_for("extras.ver_tiposmiembros")}}">Cancelar</a>
            </div>
            <div class="col-2"></div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endif %}

app/templates/extras/tiposmiembros/base_tiposmiembros.html
<!-- app/templates/extras/tiposmiembros/base_tiposmiembros.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Churching - Tipos de Miembros{% endblock %}

{% block body %}
{% if current_user.is_authenticated %}
{# En general a todo menos a Seguimiento y Ausencias pueden acceder Editores y Admin #}
{% if current_user.get_urole() >= 1 %}

{% include "home/_sidebar.html" %}

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

  <!-- Main Content -->
  <div id="content">

    {% include "home/_topbar.html" %}

    {% if flag_listar %}
      {% include "extras/tiposmiembros/tabla_tiposmiembros.html" %}
      <script src="{{ url_for('static', filename='js/extras_bprint.min.js') }}"></script>
    {% else %}
      {% include "extras/tiposmiembros/agregar_editar_tipomiembro.html" %}
    {% endif %}
  </div>
  <!-- End of Main Content -->

  {% include "home/_footer.html" %}

</div>
<!-- End of Content Wrapper -->
{% endif %}
{% endif %}
{% endblock %}

app/templates/extras/tiposmiembros/tabla_tiposmiembros.html
<!-- app/templates/extras/tiposmiembros/tabla_tiposmiembros.html -->

{% if current_user.is_authenticated %}
{# En general a todo menos a Seguimiento y Ausencias pueden acceder Editores y Admin #}
{% if current_user.get_urole() >= 1 %}

{% set nombre = 'Tipo de Miembro' %}
{% set nombres = 'Tipos de Miembros' %}

<!-- Begin Page Content -->
<div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 my-3 alert alert-primary"> {{nombres}} </h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <!-- <strong>Title</strong> --> {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="card shadow mb-4">
                <div class="card-body">
                        <h5 class="card-title">
                            Puedes crear, modificar y/o borrar {{nombres}}. Ten en cuenta que no puedes borrar un {{nombre}} que tenga personas vinculadas
                        </h5>

                {% if tiposmiembros %}

                    <div class="text-right mu-2 mb-4">
                            <a href="{{url_for("extras.crear_tipomiembro")}}" class="btn btn-primary btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fa fa-plus centered"></i>
                            </span>
                            <span class="text">Crear {{nombre}}</span>
                        </a>
                    </div>
            <div class="table-responsive">
                <table id="tblistarTiposMiembros" class="table table-bordered table-striped" id="dataTable" width="100%"
                    cellspacing="0">
                    <thead class="thead-dark">
                        <tr class="text-center">
                            <th scope="col">Id</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Descripci&oacute;n</th>
                            <th scope="col"># de Personas</th>
                            <th scope="col">Modificar</th>
                            <th scope="col">Borrar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tipomiembro in tiposmiembros %}
                        <tr>
                            <td scope="row" class="text-center"> {{ tipomiembro.id }} </td>
                            <td> {{ tipomiembro.nombre_tipomiembro }} </td>
                            <td> {{ tipomiembro.descripcion_tipomiembro }} </td>
                            <td class="text-center">
                                {% if tipomiembro.miembros %}
                                {{ tipomiembro.miembros|count() }}
                                {% else %}
                                0
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{{ url_for('extras.modif_tipomiembro', id=tipomiembro.id) }}">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="{{ url_for('extras.borrar_tipomiembro', id=tipomiembro.id) }}">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% else %}
    <div class="text-center">
        <h3> No se han agregado Tipos de Miembros. </h3>
        <hr class="intro-divider">
    </div>
    {% endif %}

</div>
<!-- /.container-fluid -->

{% endif %}
{% endif %}