app/home/forms.py
# app/home/forms.py
# coding: utf-8

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired, Length


class BusquedaForm(FlaskForm):
    """
    Formulario de busqueda rapida
    """

    cadena = StringField(u'cadena de busqueda',
                         validators=[InputRequired(),
                                     Length(min=3, max=100)])
    submit = SubmitField(u'Aceptar')

app/home/__init__.py
# app/home/__init__.py
# coding: utf-8

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py
# coding: utf-8


from flask_login import current_user, login_required, user_logged_in
from flask import redirect, url_for, render_template

from app.home import home
from app import db
from app.models import Miembro, Familia, GrupoCasero
from sqlalchemy import and_, func


@home.route('/')
def homepage():
    """
    Pagina de Inicio / Bienvenida
    """

    # si no está logado mandar a login
    if not user_logged_in:
        return redirect(url_for('auth.login'))
    else:
        return redirect(url_for('home.hub'))


@home.route('/noaccess')
@login_required
def noaccess():
    """
    Pagina de Usuario NO ADMIN & NO EDITOR logado. Por ahora no muestra nada.
    Solo un mensaje diciendo que no es admin
    """
    return render_template('home/index_noaccess.html')


@home.route('/hub')
@login_required
def hub():
    """
    Redirige al dashboard correcto segun rol
    """

    if (current_user.get_urole() == 2):
        return redirect(url_for('home.dashboard_admin'))
    elif (current_user.get_urole() == 1):
        return redirect(url_for('home.dashboard_editor'))
    else:
        return redirect(url_for('home.noaccess'))


@home.route('/dashboard_admin', methods=['GET', 'POST'])
@login_required
def dashboard_admin():
    """
    Pagina de panel de control de administracion
    Esta es la pagina principal de donde se va a todos lados
    """
    # prevent non-admins from accessing the page
    if not current_user.is_admin():
        return redirect(url_for('home.noaccess'))

    panel_p = datos_personas()
    panel_f = datos_familias()
    panel_gc = datos_gruposcaseros()
    return render_template('home/index_admin.html',
                           panel_p=panel_p, panel_f=panel_f,
                           panel_gc=panel_gc)


@home.route('/dashboard_editor')
@login_required
def dashboard_editor():
    """
    Pagina de panel de control de edicion
    restringe el acceso a cosas privadas de las personas como el seguimiento
    """

    if not current_user.get_urole() == 1:
        return redirect(url_for('home.noaccess'))

    panel_p = datos_personas()
    panel_f = datos_familias()
    panel_gc = datos_gruposcaseros()
    return render_template('home/index_editor.html',
                           panel_p=panel_p, panel_f=panel_f,
                           panel_gc=panel_gc)


def datos_personas():
    total_personas = db.session.query(Miembro).count()
    total_miembros = db.session.query(Miembro)\
                       .filter(Miembro.id_tipomiembro == 1).count()
    total_asistentes = db.session.query(Miembro)\
                         .filter(Miembro.id_tipomiembro == 2).count()
    total_otros = db.session.query(Miembro)\
                    .filter(and_(Miembro.id_tipomiembro != 1,
                                 Miembro.id_tipomiembro != 2)).count()

    return [total_personas, total_miembros, total_asistentes, total_otros]


def datos_familias():
    from datetime import date

    today = date.today()

    total_familias = db.session.query(Familia).count()

    total_adultos = db.session.query(Miembro)\
                      .filter(func.datediff(today, Miembro.fecha_nac) > 25)\
                      .count()

    total_jovenes = db.session.query(Miembro)\
                      .filter(and_(func.datediff(today, Miembro.fecha_nac) <= 25,
                                   func.datediff(today, Miembro.fecha_nac) >= 13))\
                      .count()
    total_ninios = db.session.query(Miembro)\
                     .filter(func.datediff(today, Miembro.fecha_nac) < 13)\
                     .count()

    return [total_familias, total_adultos, total_jovenes, total_ninios]


def datos_gruposcaseros():
    total_gc = db.session.query(GrupoCasero).count()
    total_personas = db.session.query(Miembro)\
                       .filter(Miembro.id_grupocasero.isnot(None)).count()

    grupos = db.session.query(GrupoCasero.nombre_grupo)\
                       .outerjoin(Miembro,
                                  GrupoCasero.id ==
                                  Miembro.id_grupocasero)\
                       .add_columns(func.count(Miembro.id))\
                       .group_by(GrupoCasero.nombre_grupo)\
                       .all()
    print("-----------", grupos)
    return [total_gc, total_personas, grupos]




app/templates/home/_footer.html
<!-- app/templates/home/_footer.html -->

<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Churching 2019 - Iglesia Cristiana Evang&eacute;lica de Chamart&iacute;n</span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/templates/home/_header.html
<!-- app/templates/home/_header.html -->

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{{ title }} </title>

  <!-- Custom fonts for this template-->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" rel="stylesheet" type="text/css">
  <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css">
  <link href="https://cdn.datatables.net/select/1.3.0/css/select.bootstrap4.min.css" rel="stylesheet" type="text/css">
  <link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css">

  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico', _external=True) }}">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('static', filename='css/sb-admin-2.min.css', _external=True) }}" rel="stylesheet">

  {# incluir js scripts #}
{% include "home/_jsincludes_top.html" %}

</head>

app/templates/home/_jsinclude_bottom.html
<!-- Custom scripts for all pages-->
<script src="{{ url_for('static', filename='js/sb-admin-2.min.js', _external=True) }}"></script>

app/templates/home/_jsincludes.html
<!-- app/templates/home/_jsincludes.html -->

<!-- Bootstrap core JavaScript-->
<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

app/templates/home/_jsincludes_top.html
<!-- app/templates/home/_jsincludes.html -->

<!-- Bootstrap core JavaScript-->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
			  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
			  crossorigin="anonymous"></script><!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

app/templates/home/_sidebar.html
<!-- app/templates/home/_sidebar.html -->

<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <div class="sidebar-brand d-flex align-items-center justify-content-center">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-cross"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Churching<sup></sup></div>
  </div>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{{url_for("home.homepage")}}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Panel de Control</span>
    </a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Gesti&Oacute;n de Personas
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePer" aria-expanded="true"
      aria-controls="collapseTwo">
      <i class="fas fa-fw fa-user"></i>
      <span>Personas</span>
    </a>
    <div id="collapsePer" class="collapse" aria-labelledby="headingPer" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item text-wrap" href="{{ url_for('miembros.ver_miembros') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Personas
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('familias.ver_familias_asignar') }}">
          <i class="fas fa-users fa-sm fa-fw mr-2 text-gray-400"></i>
          Asignar Personas a Familias
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('ggcc.ver_ggcc_asignar') }}">
          <i class="fas fa-people-carry fa-sm fa-fw mr-2 text-gray-400"></i>
          Asignar Personas a GGCC
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('miembros.listar_asignar_roles') }}">
            <i class="fas fa-dice-d20 fa-sm fa-fw mr-2 text-gray-400"></i>
            Asignar Roles a Personas
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('miembros.listar_asignar_roles') }}">
            <i class="fas fa-project-diagram fa-sm fa-fw mr-2 text-gray-400"></i>
            Asignar Personas a Ministerios
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('miembros.listar_asignar_roles') }}">
            <i class="fas fa-chalkboard-teacher fa-sm fa-fw mr-2 text-gray-400"></i>
            Asignar Personas a Clases/Talleres
        </a>

      </div>
    </div>
  </li>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseFam" aria-expanded="true"
        aria-controls="collapseTwo">
        <i class="fas fa-fw fa-users"></i>
        <span>Familias</span>
      </a>
      <div id="collapseFam" class="collapse" aria-labelledby="headingFam" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <a class="collapse-item text-wrap" href="{{ url_for('familias.ver_familias') }}">
            <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
            Gestionar Familias
          </a>
          <a class="collapse-item text-wrap" href="{{ url_for('familias.ver_familias_asignar') }}">
            <i class="fas fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>
            Agregar o quitar integrantes
          </a>
        </div>
      </div>
    </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Gesti&Oacute;n de Grupos y Ministerios
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseGGCC" aria-expanded="true"
      aria-controls="collapsePages">
      <i class="fas fa-fw fa-people-carry"></i>
      <span>Grupos Caseros</span>
    </a>
    <div id="collapseGGCC" class="collapse" aria-labelledby="headingGGCC" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item text-wrap" href="{{ url_for('ggcc.ver_ggcc') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Grupo Casero
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('ggcc.ver_ggcc_asignar') }}">
          <i class="fas fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>
          Agregar integrantes
        </a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseRol" aria-expanded="true"
      aria-controls="collapsePages">
      <i class="fas fa-fw fa-bullseye"></i>
      <span>Responsabiliades</span>
    </a>
    <div id="collapseRol" class="collapse" aria-labelledby="headingRol" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item text-wrap" href="{{ url_for('roles.ver_roles', flag='R') }}">
          <i class="fas fa-dice-d20 fa-sm fa-fw mr-2 text-gray-500"></i>
          Gestionar Roles
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('roles.ver_roles', flag='M') }}">
          <i class="fas fa-project-diagram fa-sm fa-fw mr-2 text-gray-500"></i>
          Gestionar Ministerios
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('roles.ver_roles', flag='C') }}">
          <i class="fas fa-chalkboard-teacher  fa-sm fa-fw mr-2 text-gray-500"></i>
          Gestionar Clases y Talleres
        </a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Gesti&Oacute;n de Datos Extras
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCat" aria-expanded="true"
      aria-controls="collapsePages">
      <i class="fas fa-fw fa-database"></i>
      <span>Categor&iacute;as</span>
    </a>
    <div id="collapseCat" class="collapse" aria-labelledby="headingCat" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item text-wrap" href="{{ url_for('extras.ver_estadosciviles') }}">
          <i class="fas fa-ring fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Estados Civiles
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('extras.ver_tiposmiembros') }}">
          <i class="fas fa-user-tag fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Tipos de Miembros
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('extras.ver_rolesfamiliares') }}">
          <i class="fas fa-baby fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Roles Familiares
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('extras.ver_tiposfamilias') }}">
          <i class="fas fa-tags fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Tipos de Familias
        </a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Seguimiento e Informes
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseSeg" aria-expanded="true"
      aria-controls="collapsePages">
      <i class="fas fa-fw fa-compass"></i>
      <span>Seguimientos & Ausencias</span>
    </a>
    <div id="collapseSeg" class="collapse" aria-labelledby="headingSeg" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        {% if current_user.get_urole() == 2 %}
        <a class="collapse-item text-wrap" href="{{ url_for('seguimientos.ver_seguimientos') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Seguimientos
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('seguimientos.consulta_seguimientos') }}">
          <i class="fas fa-glasses fa-sm fa-fw mr-2 text-gray-400"></i>
          Consultar Seguimientos
        </a>
        {% endif %}
        <a class="collapse-item text-wrap" href="{{ url_for('asistencias.ver_asistencias') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Gestionar Asistencia
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('asistencias.consulta_asistencias') }}">
          <i class="fas fa-calendar fa-sm fa-fw mr-2 text-gray-400"></i>
          Consultar Asistencia
        </a>
      </div>
    </div>
  </li>


  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInf" aria-expanded="true"
      aria-controls="collapsePages">
      <i class="fas fa-fw fa-scroll"></i>
      <span>Informes</span>
    </a>
    <div id="collapseInf" class="collapse" aria-labelledby="headingInf" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item text-wrap" href="{{ url_for('informes.informe_personas') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Personas
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('informes.informe_familias') }}">
          <i class="fas fa-glasses fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Familias
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('informes.informe_ggcc') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Grupos Caseros
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('informes.informe_responsables') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Responsables
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('informes.informe_ministerios') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Ministerios
        </a>
        <a class="collapse-item text-wrap" href="{{ url_for('informes.informe_clases') }}">
          <i class="fas fa-plus fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Clases y Talleres
        </a>
        {% if current_user.get_urole() == 2 %}
        <a class="collapse-item text-wrap" href="cards.html">
          <i class="fas fa-calendar fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Asistencias
        </a>
        <a class="collapse-item text-wrap" href="cards.html">
          <i class="fas fa-calendar fa-sm fa-fw mr-2 text-gray-400"></i>
          Informe Seguimientos
        </a>
        {% endif %}
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->

app/templates/home/_topbar.html
         <!-- Topbar -->
         <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                  <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Search -->
                    <div class="input-group">
                    <input name="topsearch_texto" id="topsearch_texto"
                           type="text" class="form-control bg-light border-0 small"
                           placeholder="Buscar personas" aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button name="topsearch_button" id="topsearch_button" class="btn btn-primary btn-block">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>


                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                  <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                  <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                      <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                          <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                          <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                              <i class="fas fa-search fa-sm"></i>
                            </button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </li>

                                 <div class="topbar-divider d-none d-sm-block"></div>

                  <!-- Nav Item - User Information -->
                  <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ current_user.username }}</span>
                      <i class="fas fa-user-circle fa-3x"></i>
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Cerrar Sesi&oacute;n
                      </a>
                    </div>
                  </li>

                </ul>

              </nav>
              <!-- End of Topbar -->

app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Sin acceso de administrador</h1>
                    <h3>Necesita ser administrador para acceder a los datos</h3>
                    <hr class="intro-divider">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index_admin.html
<!-- app/templates/home/index_admin.html -->

{% extends "base.html" %}
{% block title %}Churching - Inicio{% endblock %}

{% block body %}
  {% if current_user.is_authenticated %}
    {% if current_user.is_admin %}

      {% include "home/_sidebar.html" %}

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

          {% include "home/_topbar.html" %}

          {% include "home/contenido.html" %}

        </div>
        <!-- End of Main Content -->

      {% include "home/_footer.html" %}

      </div>
      <!-- End of Content Wrapper -->
    {% endif %}
  {% endif %}
{% endblock %}

app/templates/home/index_editor.html
<!-- app/templates/home/index_editor.html -->

{% extends "base.html" %}
{% block title %}Churching - Inicio{% endblock %}

{% block body %}
  {% if current_user.is_authenticated %}
    {% if current_user.is_admin %}

      {% include "home/_sidebar.html" %}

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

          {% include "home/_topbar.html" %}

          {% include "home/contenido.html" %}

        </div>
        <!-- End of Main Content -->

      {% include "home/_footer.html" %}

      </div>
      <!-- End of Content Wrapper -->
    {% endif %}
  {% endif %}
{% endblock %}

app/templates/home/index_noaccess.html
<!-- app/templates/home/index_noaccess.html -->

<html>

{# incluir cabecera #}
{% include "home/_header.html" %}


<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <div class="jumbotron">
            <h2 class="display-4">Lo sentimos</h2>
            <p class="lead">Solamente los usuarios administradores y editores pueden acceder al sistema</p>
            <hr class="my-4">
            <p>Si crees que deberías tener acceso ponte en contacto en <a
                    href="emailto:admin@ichamartin.org">admin@ichamartin.org</a></p>
            <a class="btn btn-primary btn-lg" role="button" href="{{ url_for('auth.logout') }}">Logout</a>
        </div>

        <!-- Card image -->
        <div class="view overlay rounded-top">
            <img src="{{ url_for('static', filename='img/noaccess.jpg') }}" class="img-fluid" alt="No Access">
            <a href="#">
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>
    </div>

    {% include "home/_jsinclude_bottom.html" %}

</body>




</html>