app/roles/forms.py
# app/roles/forms.oy
# coding: utf-8

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class RolForm(FlaskForm):
    """
    Form para agregar o modificar un rol, ministerio o clase
    """
    nombre_rol = StringField(u'Nombre', validators=[DataRequired()])
    descripcion_rol = StringField(u'Descripción')
    tipo_rol = StringField(u'Tipo')
    submit = SubmitField(u'Aceptar')

app/roles/__init__.py
# app/roles/__init__.py

from flask import Blueprint

roles = Blueprint('roles', __name__)

from . import views

app/roles/views.py
# app/roles/views.py
# coding: utf-8

from flask import flash
from flask import redirect, render_template, url_for
from flask_login import current_user, login_required

from app.roles import roles
from app.roles.forms import RolForm

from app import db
from app.models import Rol


def check_edit_or_admin():
    """
    Si no es admin o editor lo manda al inicio
    """
    if not current_user.get_urole() >= 1:
        return redirect(url_for("home.hub"))


# SECCION: ***** Rol: PASTOR, ANCIANO; DIACONO, LIDER GRUPO CASERO *****

@roles.route('/roles/<string:flag>', methods=['GET'])
@login_required
def ver_roles(flag):
    """
    Ver una lista de todos los roles
     --- aunque es la misma tabla se mostrarán los distintos
     --- tipos de roles, misnitreros, clases, en distintas pantallas
    """
    check_edit_or_admin()

    # si flag viene vacio ir por defecto a Roles
    if (flag == ''):
        flag = 'R'

    # de arranque carga el listado
    flag_listar = True

    query_roles = Rol.query.filter_by(tipo_rol=flag)

    return render_template('roles/base_roles.html',
                           roles=query_roles,
                           flag_listar=flag_listar,
                           flag_tiporol=flag)


@roles.route('/roles/crear/<string:flag>',
             methods=['GET', 'POST'])
@login_required
def crear_rol(flag):
    """
    Agregar un Rol a la Base de Datos
    """
    check_edit_or_admin()

    # Variable para el template. Para decirle si es Alta o Modif
    flag_crear = True
    flag_listar = False

    form = RolForm()

    if form.validate_on_submit():
        obj_rol = Rol(nombre_rol=form.nombre_rol.data,
                      descripcion_rol=form.descripcion_rol.data,
                      tipo_rol=flag)
        try:
            db.session.add(obj_rol)
            db.session.commit()
            flash('Has guardado los datos correctamente', 'success')
        except Exception as e:
            flash('Error: ', e, ' danger')

        return redirect(url_for('roles.ver_roles', flag=flag))

    return render_template(
                'roles/base_roles.html',
                add_roles=flag_crear, flag_listar=flag_listar,
                flag_tiporol=flag, form=form)


@roles.route('/roles/modificar/<int:id>/<string:flag>',
             methods=['GET', 'POST'])
@login_required
def modif_rol(id, flag):
    """
    Modificar un rol
    """
    check_edit_or_admin()

    flag_crear = False
    flag_listar = False

    obj_rol = Rol.query.get_or_404(id)
    form = RolForm(obj=obj_rol)
    if form.validate_on_submit():
        obj_rol.nombre_rol = form.nombre_rol.data
        obj_rol.descripcion_rol = form.descripcion_rol.data
        obj_rol.tipo_rol = flag
        try:
            db.session.commit()
            flash('Has modificado los datos correctamente', 'success')
        except Exception as e:
            flash('Error: ' + str(e), 'danger')

        return redirect(url_for('roles.ver_roles', flag=flag))

    form.nombre_rol.data = obj_rol.nombre_rol
    form.descripcion_rol.data = obj_rol.descripcion_rol
    return render_template(
                'roles/base_roles.html',
                add_roles=flag_crear, flag_listar=flag_listar,
                form=form, rol=obj_rol, flag_tiporol=flag)


@roles.route('/roles/borrar/<int:id>/<string:flag>',
             methods=['GET'])
@login_required
def borrar_rol(id, flag):
    """
    Borrar un rol
    """
    check_edit_or_admin()

    obj_rol = Rol.query.get_or_404(id)
    db.session.delete(obj_rol)
    try:
        db.session.commit()
        flash('Has borrado los datos correctamente', 'success')
    except Exception as e:
        flash('Error: ' + str(e), 'danger')

    return redirect(url_for('roles.ver_roles', flag=flag))



app/templates/roles/agregar_editar_rol.html
<!-- app/templates/roles/agregar_editar_rol.html -->

{% if current_user.is_authenticated %}
{# En general a todo menos a Seguimiento y Ausencias pueden acceder Editores y Admin #}
{% if current_user.get_urole() >= 1 %}


{%  if (flag_tiporol == 'R') %}
{%     set nombre = 'Rol' %}
{%  elif (flag_tiporol == 'M') %}
{%     set nombre = 'Ministerio' %}
{%  elif (flag_tiporol == 'C') %}
{%     set nombre = 'Clase' %}
{% endif %}

{% if add_rol %}
{%     set modo = 'Agregar' %}
{% else %}
{%     set modo = 'Modificar' %}
{% endif %}


<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- Page Heading -->
  <h1 class="h3 my-3 alert alert-primary"> {{modo}} {{nombre}} </h1>
  <div class="col-12">
    <div class="card shadow">
      <h5 class="card-header py-3">
          Datos
      </h5>
      <div class="card-body">
        <form class="user" method="POST" role="form" action="">
          {{ form.csrf_token }}
          <div class="form-group">
            {{form.nombre_rol.label}}
            {{ form.nombre_rol(class_="form-control form-control-user") }}
          </div>
          <div class="form-group">
            {{form.descripcion_rol.label}}
            {{ form.descripcion_rol(class_="form-control form-control-user") }}
          </div>
          <div class="form-group">
            {{form.tipo_rol.label}}
            {{ form.tipo_rol(class_="form-control form-control-user",readonly=true,value=nombre) }}
          </div>
          <div class="row">
            <div class="col-2"></div>
            <div class="col-4">
              <input type="submit" id="submit" name="submit" class="font-weight-bold btn btn-primary btn-block btn-lg"
                value="Guardar" />
            </div>
            <div class="col-4">
              <a class="font-weight-bold btn btn-danger btn-lg btn-block"
                href="{{ url_for('roles.ver_roles', flag=flag_tiporol) }}">Cancelar</a>
            </div>
            <div class="col-2"></div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endif %}

app/templates/roles/base_roles.html
<!-- app/templates/roles/base_roles.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}
{% if flag_tiporol=='R' %}
  Churching - Roles Familiares
{% elif flag_tiporol=='M' %}
  Churching - Ministarios
{% elif flag_tiporol=='C' %}
  Churching - Clases
{% endif %}
{% endblock %}

{% block body %}
{% if current_user.is_authenticated %}
{# En general a todo menos a Seguimiento y Ausencias pueden acceder Editores y Admin #}
{% if current_user.get_urole() >= 1 %}

{% include "home/_sidebar.html" %}

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

  <!-- Main Content -->
  <div id="content">

    {% include "home/_topbar.html" %}

    {% if flag_listar %}
      {% include "roles/tabla_roles.html" %}
      <script src="{{ url_for('static', filename='js/roles_bprint.min.js') }}"></script>
    {% else %}
      {% include "roles/agregar_editar_rol.html" %}
    {% endif %}
  </div>
  <!-- End of Main Content -->

  {% include "home/_footer.html" %}

</div>
<!-- End of Content Wrapper -->
{% endif %}
{% endif %}
{% endblock %}

app/templates/roles/tabla_roles.html
<!-- app/templates/roles/tabla_roles.html -->

{% if current_user.is_authenticated %}
{# En general a todo menos a Seguimiento y Ausencias pueden acceder Editores y Admin #}
{% if current_user.get_urole() >= 1 %}

{%  if (flag_tiporol == 'R') %}
{%     set nombre = 'Rol' %}
{%     set nombres = 'Roles' %}
{%  elif (flag_tiporol == 'M') %}
{%     set nombre = 'Ministerio' %}
{%     set nombres = 'Ministerios' %}
{%  elif (flag_tiporol == 'C') %}
{%     set nombre = 'Clase' %}
{%     set nombres = 'Clase' %}
{% endif %}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 my-3 alert alert-primary"> {{ nombres }} </h1>
    {% with messages = get_flashed_messages(with_categories=true) %}
    <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        <!-- <strong>Title</strong> --> {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="card shadow mb-4">
        <div class="card-body">
                <h5 class="card-title">
                    Puedes crear, modificar y/o borrar {{nombres}}. Ten en cuenta que no puedes borrar un {{nombre}} que tenga personas vinculadas
                </h5>

        {% if roles %}

            <div class="text-right mu-2 mb-4">
                <a href="{{ url_for("roles.crear_rol", flag=flag_tiporol) }}" class="btn btn-primary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fa fa-plus centered"></i>
                    </span>
                    <span class="text">Crear {{ nombre }}</span>
                </a>
            </div>

            <div class="table-responsive">
                <table id="tbListarRoles" class="table table-bordered table-striped" id="dataTable" width="100%"
                        cellspacing="0">
                    <thead class="thead-dark">
                        <tr class="text-center">
                            <th scope="col">Id</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Descripci&oacute;n</th>
                            <th scope="col">Tipo</th>
                            <th scope="col"># de Personas</th>
                            <th scope="col">Modificar</th>
                            <th scope="col">Borrar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for rol in roles %}
                        <tr>
                            <td scope="row" class="text-center"> {{ rol.id }} </td>
                            <td> {{ rol.nombre_rol }} </td>
                            <td> {{ rol.descripcion_rol }} </td>
                            <td class="text-center"> {{nombre}} </td>
                            <td class="text-center">
                                {% if rol.miembros %}
                                    {{ rol.miembros|count() }}
                                {% else %}
                                     0
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{{ url_for('roles.modif_rol', id=rol.id, flag=flag_tiporol) }}">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="{{ url_for('roles.borrar_rol', id=rol.id, flag=flag_tiporol) }}">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="text-center">
            <h3> No se han agregado datos </h3>
            <hr class="intro-divider">
            </div>
           {% endif %}
        </div>
    </div>
</div>
<!-- /.container-fluid -->

{% endif %}
{% endif %}